name: Build Frontend From Host Path

on:
  push:
    branches: ["master"]

jobs:
  frontend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build docker image (frontend) from host folder
        run: docker buildx build "/home/ahmad-jaber/server/frontend/frontendTest" -t frontendimage:latest --load

      - name: Run compose service (frontend)
        working-directory: ./server
        run: docker compose up -d frontend
