name: Build Docker Image In Host

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Access Docker File In Host
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build docker image (frontend)
        working-directory: ./server/forntend/frontendtest
        run: docker buildx build . -t frontendimage --load

      - name: Run compose service (frontend)
        working-directory: ./server
        run: docker compose up -d frontend
